apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-management
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  REDIS_TTL: "3600"
  CORS_ORIGINS: "*"
  CORS_CREDENTIALS: "true"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_HEADERS: "*"