apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-service
  template:
    metadata:
      labels:
        app: grade-service
    spec:
      containers:
      - name: grade-service
        image: gcr.io/cs436termproject-460018/grade-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: grade-service
spec:
  selector:
    app: grade-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
