apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: student-management
  labels:
    app: redis
spec:
  replicas: 1 # Kustomize overlay'lerde ezilebilir
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "$(date +%Y%m%d%H%M%S)"
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest # Redis imajı
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
