apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: student-management
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379 # Cluster içi erişim portu
    targetPort: 6379 # Container portu
