apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: cs436-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: gcr.io/cs436termproject-460018/course-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: "10.128.0.2"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "12345678"
        - name: DB_NAME
          value: "student_management"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m" 