apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: student-management
spec:
  selector:
    app: course-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP 