apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: student-management
  labels:
    app: course-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  strategy: {}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "$(date +%Y%m%d%H%M%S)"
      creationTimestamp: null
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: gcr.io/cs436termproject-460018/course-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "10.128.0.2"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
