apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: student-management
  labels:
    app: course-service
spec:
  selector:
    app: course-service
  ports:
  - protocol: TCP
    port: 8001 # Cluster içi erişim portu
    targetPort: 8001 # Container portu
