apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: student-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 2
  maxReplicas: 10 # Kustomize overlay'lerde ezilebilir
  metrics:
  - type: Resource
    resource:
      name: cpu
      averageUtilization: 50
