apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: student-management
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80 # Cluster içi erişim portu
    targetPort: 80 # Container portu
