apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: student-management
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
