apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: student-management
spec:
  selector:
    app: student-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP 