apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grade-service-hpa
  namespace: student-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grade-service
  minReplicas: 1
  maxReplicas: 5 # Kustomize overlay'lerde ezilebilir
  metrics:
  - type: Resource
    resource:
      name: cpu
      averageUtilization: 60
