apiVersion: v1
kind: Service
metadata:
  name: grade-service
  namespace: student-management
  labels:
    app: grade-service
spec:
  selector:
    app: grade-service
  ports:
  - protocol: TCP
    port: 8002 # Cluster içi erişim portu
    targetPort: 8002 # Container portu
