apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-service
  namespace: student-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grade-service
  template:
    metadata:
      labels:
        app: grade-service
    spec:
      containers:
      - name: grade-service
        image: gcr.io/cs436-460908/grade-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database-url
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-name
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"