apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-service
  namespace: cs436-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grade-service
  template:
    metadata:
      labels:
        app: grade-service
    spec:
      containers:
      - name: grade-service
        image: gcr.io/cs436termproject-460018/grade-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: DB_HOST
          value: "10.128.0.2"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "12345678"
        - name: DB_NAME
          value: "student_management"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m" 