apiVersion: v1
kind: Service
metadata:
  name: grade-service
  namespace: student-management
spec:
  selector:
    app: grade-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP 