apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: student-management
  labels:
    app: student-service
spec:
  selector:
    app: student-service
  ports:
  - protocol: TCP
    port: 8080 # Service port
    targetPort: 8080 # Container port
  type: ClusterIP # Expose service within the cluster
