# k8s/base/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: student-management
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          # 1) UI (everything except /api)  
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          # 2) API  
          - path: /api/students
            pathType: Prefix
            backend:
              service:
                name: student-service
                port:
                  number: 80
          - path: /api/courses
            pathType: Prefix
            backend:
              service:
                name: course-service
                port:
                  number: 80
          - path: /api/grades
            pathType: Prefix
            backend:
              service:
                name: grade-service
                port:
                  number: 80
