apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-management-ingress
  namespace: student-management
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "student-management-ip"
spec:
  rules:
  - host: student-management.example.com  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api/students
        pathType: Prefix
        backend:
          service:
            name: student-service
            port:
              number: 8080
      - path: /api/courses
        pathType: Prefix
        backend:
          service:
            name: course-service
            port:
              number: 8080
      - path: /api/grades
        pathType: Prefix
        backend:
          service:
            name: grade-service
            port:
              number: 8080