apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        # API routes with regex to handle trailing slashes
        - path: /api/students(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: student-service
              port:
                number: 80

        - path: /api/courses(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: course-service
              port:
                number: 80

        - path: /api/grades(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: grade-service
              port:
                number: 80

        # Frontend - everything else
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: frontend
              port:
                number: 80