apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: student-management
  annotations:
    # Google Cloud Ingress Controller için annotation'lar
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
    # Backend servisi için timeout ayarı (isteğe bağlı)
    # ingress.gce.kubernetes.io/backend-timeout: "60s"
    # Eğer global statik IP kullanacaksanız:
    # kubernetes.io/ingress.global-static-ip-name: YOUR_STATIC_IP_NAME
    # Add any other necessary annotations for SSL, etc.
spec:
  rules:
  - http:
      paths:
      # Frontend trafiği
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      # Backend API trafiği
      - path: /api/students
        pathType: Prefix
        backend:
          service:
            name: student-service
            port:
              number: 80
      - path: /api/courses
        pathType: Prefix
        backend:
          service:
            name: course-service
            port:
              number: 80
      - path: /api/grades
        pathType: Prefix
        backend:
          service:
            name: grade-service
            port:
              number: 80

