apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  rules:
  - http:
      paths:
        # API routes - exact paths without regex
        - path: /api/students
          pathType: Prefix
          backend:
            service:
              name: student-service
              port:
                number: 80

        - path: /api/courses
          pathType: Prefix
          backend:
            service:
              name: course-service
              port:
                number: 80

        - path: /api/grades
          pathType: Prefix
          backend:
            service:
              name: grade-service
              port:
                number: 80

        # Frontend - everything else (no regex rewrite)
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80