apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmaps/
- secrets/
- student-service/
- course-service/
- grade-service/
- frontend/
- redis/
- ingress.yaml
# Ek base kaynakları buraya eklenebilir 