apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmaps/
- secrets/
- student-service/deployment.yaml
- student-service/service.yaml
- student-service/hpa.yaml
- course-service/deployment.yaml
- course-service/service.yaml
- course-service/hpa.yaml
- grade-service/deployment.yaml
- grade-service/service.yaml
- grade-service/hpa.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- frontend/hpa.yaml
- redis/
- ingress.yaml