apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmaps/app-config.yaml
- secrets/db-credentials.yaml # Dikkat: hassas bilgi içerir, yönetimi önemlidir
- backend/course/deployment.yaml
- backend/course/hpa.yaml
- backend/course/service.yaml
- backend/grade/deployment.yaml
- backend/grade/hpa.yaml
- backend/grade/service.yaml
- backend/student/deployment.yaml
- backend/student/hpa.yaml
- backend/student/service.yaml
- frontend/deployment.yaml
- frontend/hpa.yaml
- frontend/service.yaml
- redis/deployment.yaml
- redis/service.yaml
- ingress.yaml
# Ek base kaynakları buraya eklenebilir 